language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-readme' ]; then cd .. && eval "mv $currentfolder generator-readme" && cd generator-readme; fi

